# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(450, 560)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(450, 560))
        MainWindow.setMaximumSize(QtCore.QSize(451, 561))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.resetButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(10, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.resetButton.setFont(font)
        self.resetButton.setObjectName("resetButton")
        self.prompt = QtWidgets.QLabel(parent=self.centralwidget)
        self.prompt.setGeometry(QtCore.QRect(120, 10, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.prompt.setFont(font)
        self.prompt.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.prompt.setObjectName("prompt")
        self.board = QtWidgets.QTableView(parent=self.centralwidget)
        self.board.setGeometry(QtCore.QRect(5, 60, 441, 459))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.board.setFont(font)
        self.board.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.board.setDragDropMode(QtWidgets.QAbstractItemView.DragDropMode.NoDragDrop)
        self.board.setCornerButtonEnabled(False)
        self.board.setObjectName("board")
        self.board.horizontalHeader().setVisible(False)
        self.board.horizontalHeader().setHighlightSections(False)
        self.board.verticalHeader().setVisible(False)
        self.board.verticalHeader().setHighlightSections(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TicTacToe"))
        self.resetButton.setText(_translate("MainWindow", "Reset"))
        self.prompt.setText(_translate("MainWindow", "Prompt"))
